use_frameworks!

platform :ios, '8.0'

target 'RYNCategory_Example' do
  pod 'RYNCategory', :path => '../'

  target 'RYNCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
